language: rust
cache: cargo
dist: trusty
sudo: false

addons:
  apt:
    packages:
      - fakeroot
      - musl-dev
      - musl-tools

env:
  global:
    - PROJECT_NAME=cargo-watch

matrix:
  include:
    # Default test+release versions
    - os: windows
      rust: stable
      env: TARGET=x86_64-pc-windows-msvc
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu

    # Extra targets, also released
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl
    - os: linux
      rust: stable
      env: TARGET=i686-unknown-linux-musl

    # Non-critical, best-effort
    - os: windows
      rust: nightly
      env: TARGET=x86_64-pc-windows-msvc
    - os: linux
      rust: nightly
      env: TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: nightly
      env: TARGET=x86_64-apple-darwin
    - os: windows
      rust: stable
      env: TARGET=x86_64-pc-windows-gnu

  allow_failures:
    - rust: nightly
    - env: TARGET=x86_64-pc-windows-gnu
  fast_finish: true

before_script: rustup target add $TARGET || echo ok
script:
  - cargo check --target $TARGET
  - cargo build --target $TARGET
  - cargo test --target $TARGET

before_deploy: ./.package $TRAVIS_TAG $TARGET
deploy:
  provider: releases
  api_key:
    secure: LXi48d/kJVntJKV0SjKk9HHMc3IzxQt+3YY2PDDB7toQmVOf6mVdaRHSLQ5p08g6R4/z2hzsqDaKC7lvy1E5BuQotMJ9b4uw5ZiAE534CHr2IgQIwTJvV4gweC9fwZk8Ln8k3PY0Z9wLy/tzWaZHo9WK4IqjB4XrTOhR2vDoaq0=
  file_glob: true
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
  skip_cleanup: true
  on:
    repo: passcod/cargo-watch
    tags: true
    rust: stable
