[package]
name = "cargo-watch"
version = "7.5.0"
edition = "2018"

authors = ["Félix Saparelli <felix@passcod.name>"]
categories = ["command-line-utilities", "development-tools"]
description = "Watches over your Cargo project’s source"
homepage = "https://github.com/passcod/cargo-watch"
keywords = ["cargo", "watch", "compile", "notify"]
license = "CC0-1.0"
readme = "README.md"
repository = "https://github.com/passcod/cargo-watch"

[badges]
travis-ci = { repository = "passcod/cargo-watch" }
maintenance = { status = "passively-maintained" }

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }.tar.xz"
bin-dir = "{ name }-v{ version }-{ target }/{ bin }{ format }"
pkg-fmt = "txz"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[dependencies]
clap = "2.33.1"
log = "0.4.8"
stderrlog = "0.4.3"
watchexec = "=1.14.0"

[dev-dependencies]
assert_cmd = "1.0.1"
insta = "0.16.1"
predicates = "1.0.4"
wait-timeout = "0.2.0"
