[package]
name = "cargo-watch"
version = "7.8.1"

authors = ["Félix Saparelli <felix@passcod.name>"]
license = "CC0-1.0"
description = "Watches over your Cargo project’s source"
keywords = ["cargo", "watch", "compile", "notify"]
categories = ["command-line-utilities", "development-tools"]

documentation = "https://watchexec.github.io/docs/cargo-watch/"
homepage = "https://watchexec.github.io/#cargo-watch"
repository = "https://github.com/watchexec/cargo-watch"
readme = "README.md"

edition = "2018"
exclude = ["/.github"]

[[bin]]
name = "cargo-watch"

[dependencies]
camino = "1.0.4"
clap = "2.33.1"
log = "0.4.8"
shell-escape = "0.1.5"
stderrlog = "0.5.1"
watchexec = "1.16.1"

[dev-dependencies]
assert_cmd = "1.0.1"
insta = "1.7.1"
predicates = "2.0.0"
wait-timeout = "0.2.0"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }.tar.xz"
bin-dir = "{ name }-v{ version }-{ target }/{ bin }{ format }"
pkg-fmt = "txz"
