[package]
name = "cargo-watch"
version = "3.1.0"
authors = [
  "Félix Saparelli <me@passcod.name>",
  "Antti Keränen <detegr@gmail.com>",
  "Konstantin Stepanov <me@kstep.me>",
  "Jonathan Neuschäfer <j.neuschaefer@gmx.net>",
  "Gabor Nagy <mail@aigeruth.hu>",
  "Ivan Jager <aij+git@mrph.org>",
  "Christopher Brickley <brickley@gmail.com>",
  "Lukas Kalbertodt <lukas.kalbertodt@gmail.com>",
]

description = "Utility for cargo to compile projects when sources change"
homepage = "https://github.com/passcod/cargo-watch"
repository = "https://github.com/passcod/cargo-watch"

readme = "README.md"
license = "CC0-1.0"
keywords = [
  "cargo",
  "watch",
  "compile",
  "notify"
]

[dependencies]
docopt = "^0.6.78"
env_logger = "^0.3.2"
lazy_static = "^0.1.15"
libc = "^0.2.4"
log = "^0.3.4"
notify = "^2.5.4"
regex = "^0.1.44"
rustc-serialize = "^0.3.16"
wait-timeout = "^0.1.0"
