[package]
name = "cargo-watch"
version = "4.0.3"

authors = ["Félix Saparelli <felix@passcod.name>"]
categories = ["command-line-utilities", "development-tools"]
description = "Watches over your Cargo project’s source"
homepage = "https://github.com/passcod/cargo-watch"
keywords = ["cargo", "watch", "compile", "notify"]
license = "CC0-1.0"
readme = "README.md"
repository = "https://github.com/passcod/cargo-watch"

[dependencies]
clap = "2.22.1"
duct = "0.8.1"
env_logger = "0.3.5"
ignore = "0.1.8"
log = "0.3.6"
notify = "4.0.1"
walkdir = "1.0.7"
