[package]
name = "cargo-watch"
version = "7.6.1"

authors = ["Félix Saparelli <felix@passcod.name>"]
license = "CC0-1.0"
description = "Watches over your Cargo project’s source"
keywords = ["cargo", "watch", "compile", "notify"]
categories = ["command-line-utilities", "development-tools"]

documentation = "https://github.com/passcod/cargo-watch"
homepage = "https://github.com/passcod/cargo-watch"
repository = "https://github.com/passcod/cargo-watch"
readme = "README.md"

edition = "2018"
exclude = ["/.github"]

[badges]
maintenance = { status = "passively-maintained" }

[[bin]]
name = "cargo-watch"

[dependencies]
clap = "2.33.1"
log = "0.4.8"
stderrlog = "0.4.3"
watchexec = "=1.14.0"
shell-escape = "0.1.5"

[dev-dependencies]
assert_cmd = "1.0.1"
insta = "0.16.1"
predicates = "1.0.4"
wait-timeout = "0.2.0"

[build-dependencies]
embed-resource = "1.6.1"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }.tar.xz"
bin-dir = "{ name }-v{ version }-{ target }/{ bin }{ format }"
pkg-fmt = "txz"
