[package]
name = "cargo-watch"
version = "7.1.0"

authors = ["Félix Saparelli <felix@passcod.name>"]
categories = ["command-line-utilities", "development-tools"]
description = "Watches over your Cargo project’s source"
homepage = "https://github.com/passcod/cargo-watch"
keywords = ["cargo", "watch", "compile", "notify"]
license = "CC0-1.0"
readme = "README.md"
repository = "https://github.com/passcod/cargo-watch"

[badges]
travis-ci = { repository = "passcod/cargo-watch" }
maintenance = { status = "passively-maintained" }

[dependencies]
clap = "2.26.0"
watchexec = "1.10.0"

[dev-dependencies]
insta = "0.5.2"
assert_cmd = "0.10.2"
wait-timeout = "0.2.0"
