[package]
name = "cargo-watch"
version = "2.1.2"
authors = [
  "Félix Saparelli <felix@passcod.name>",
  "Antti Keränen <detegr@gmail.com>",
  "Konstantin Stepanov <me@kstep.me>",
  "Jonathan Neuschäfer <j.neuschaefer@gmx.net>",
]

description = "Utility for cargo to compile projects when sources change"
homepage = "https://github.com/passcod/cargo-watch"
repository = "https://github.com/passcod/cargo-watch"

readme = "README.md"
license = "CC0-1.0"
keywords = [
  "cargo",
  "watch",
  "compile",
  "notify"
]

[dependencies]
rustc-serialize = "*"
docopt = "0.6"
docopt_macros = "0.6"
regex = "*"
time = "*"

[dependencies.notify]
git = "https://github.com/passcod/rsnotify.git"
rev = "4a422a381cbc701998033898cc787c30943e929c"
